services:
  postgres:
    image: postgres:17
    environment:
      - POSTGRES_DB=Medic_DB
      - POSTGRES_USER=kevalck
      - POSTGRES_PASSWORD=admin123
    ports:
      - 5432:5432
    container_name: my_postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80

volumes:
  postgres_data:
